## YAML Template.
---
version: '3.1'

services:
  bazar:
    build: bazar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: always
    depends_on:
      bazar_bdd:
        condition: service_healthy
  bazar_bdd:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: bazar_database
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10